repos:
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.961
    hooks:
      - id: mypy
        args: [--check-untyped-defs, --ignore-missing-imports]
        additional_dependencies: [pytest, types-requests]
  - repo: https://github.com/psf/black
    rev: stable
    hooks:
      - id: black
        language_version: python3
